# myApp/docker-compose.yaml

services:
  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_API_URL=http://localhost:4000
    container_name: frontend_c
    ports:
      - '3000:3000'
  backend:
    build: ./backend
    container_name: backend_c
    ports:
      - '4000:4000'
    stdin_open: true
    tty: true
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/mydatabase
      - JWT_SECRET=supersecretjwtkeyfordev
      - ADMIN_KEY=secret_admin_key_dev
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongodb_c
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
# Add named volume for MongoDB persistence
volumes:
  mongo-data: